### ISSUE TITLE
Getting 'Cannot read property 'substr' of undefined'

### ISSUE THREAD

**Issue by acaciobrito** [willfarrell/middy-jsonapi#3]
I am having an issue on line 83( parameter: error.dataPath.substr(1)) of middy-jsonapi/index.js

My error details, for some reason, doesn't have this dataPath property. How can I force it to have this property or ignore it ?

My middy version:
```
"@middy/core": "^2.2.0",
    "@middy/http-content-negotiation": "^2.2.0",
    "@middy/http-error-handler": "^2.2.0",
    "@middy/http-json-body-parser": "^2.2.0",
    "@middy/http-response-serializer": "^2.2.0",
    "@middy/validator": "^2.2.0",
    "middy": "^0.36.0",
    "middy-jsonapi": "^2.0.0-alpha.0",
```
My middy validator schema:

```
export const createTaskSchema = {
  type: 'object',
  properties: {
    body: {
      type: 'object',
      properties: {
        appTaskListDisplayName: {type: 'string'},
        title: {type: 'string'},
        dueDateTime: {type: 'string'},
        description: {type: 'string'},
        outletId: {type: 'string'},
      },
      required: ['appTaskListDisplayName', 'title', 'dueDateTime'],
      additionalProperties: false,
    },
  },
};
```

My handler
```
export const createTaskHandler: (
  event: APIGatewayEvent,
  context: Context,
  callback: Callback
) => Promise<APIGatewayProxyResult> | void = middy(
  (createTask as unknown) as (
    event: APIGatewayEvent
  ) => Promise<APIGatewayProxyResult>
)
  .use(jsonBodyParser())
  .use(
    responseSerializer({
      serializers: [
        {
          regex: /^application\/json$/,
          serializer: ({body}) => JSON.stringify(body),
        },
      ],
      default: 'application/json',
    })
  )
  .use(jsonapi({meta: {now: new Date().toISOString()}}))
  .use(
    httpContentNegotiation({availableMediaTypes: ['application/vnd.api+json']})
  )
  .use(
    validator({
      inputSchema: createTaskSchema,
      ajvOptions: {
        coerceTypes: 'array',
        allErrors: true,
        useDefaults: true,
        $data: true,
      },
    })
  );
```

**Comment by willfarrell** [comment]
In ajv v8 (introduced into middy in v2.2.0), `dataPath` was renamed to `instancePath`. Would you like to submit a PR for this?

**Comment by acaciobrito** [comment]
I just found out about it on their changelog :P 

Yea, I will submit a PR for it.

Thanks!

**Comment by willfarrell** [comment]
Thanks. I've updated the middy changelog to call this out specifically.

**Comment by acaciobrito** [comment]
I just opened the PR.

**Comment by acaciobrito** [comment]
@willfarrell  I dont want to open another issue about it and all my info is here, but I have a question

right now I am getting

```
{'cxTaskService': {'version': '1.0'
    }, 'meta': {'now': '2021-05-14T16: 07: 13.600Z'
    }, 'errors': [
        {'status': '502', 'title': 'BadGatewayError', 'detail': 'Error when getting the tasklists: Error: Access token has expired or is not yet valid.'
        }
    ]
}
```

In the response. How can I transform this to json? My .use(responseSerializer) doesnt appear to work on it.

**Comment by willfarrell** [comment]
in middy the `onError` middleware stack goes from first to last. Order is important. There can be edge cases where this conflicts with what you need for `after`. There is an open issue for this and will be addressed in middy v3.

Any middleware stack can return a response to short circuit the stack and skip the rest.

**Comment by acaciobrito** [comment]
Sorry I did not get it what you mean and I did not find much information about it on middy?

Can you tell me how should I setup my 'createTaskHandler'?

The content-type of my responde when there are errors is 'application/vnd.api+json' but when I get success the content-type is 'application/json'

I need the error response to return as json with the double quotes.
